#Numpy Array

In [5]:
import numpy as np

a= [1,2,3,4,5,6,7,8,9,10]
print(type(a))
arr = np.array(a)
print(type(arr))

print(arr.shape)#size of the array!

<class 'list'>
<class 'numpy.ndarray'>
(10,)


In [6]:
a = [
    [1,4],
     [3,5]
]
a = np.array(a)
print(a.shape)
print(a[1][1],a[1,1])

(2, 2)
5 5


In [11]:
arr =[
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
]
arr = np.array(arr)
print(arr.shape)
print(arr[1][1][2])
print(arr[0][1][0])
print("#2d",arr.shape[0],"#1d",arr.shape[1],"#element in each 1d",arr.shape[2])

(2, 2, 3)
12
4
#2d 2 #1d 2 #element in each 1d 3


In [ ]:
a=[
     [1,2,3,4,5,6,7,8,9,10],
   [2,3,5,76,766,65,5]
]
a = np.random.random((4,6))
#a = np.random.random()
#a = np.random.radiant(low=0,high=,size)
print(a)


In [19]:
a = np.array([
    [1,2,3],
    [4,5,6]]
    )
print(a)
print(a[0:2,0:2])
print(a[1: ,1:3])
print(a[1: ,1:])

[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]
[[5 6]]
[[5 6]]


In [21]:
a = np.array([
    [1 , 2, 3, 4],
    [5 , 6, 7, 8],
    [9,10,11,12],
    [13,14,15,16],
    [17,18,19,20]
])

print(a[1:3,1:])
print(a[1: , 2: 3])
print(a[0:1+1,1: ])

[[ 6  7  8]
 [10 11 12]]
[[ 7]
 [11]
 [15]
 [19]]
[[2 3 4]
 [6 7 8]]


In [ ]:
#input 2d arr
